### ISSUE TITLE
Architecture name samd_advanced and BastWAN

### ISSUE THREAD

**Issue by ricaun** [ElectronicCats/Arduino_Boards_Index#15]
I was looking at the samd_advanced architecture name and I understand why the name SAMDLC. 

You should change to lowercase 'samdlc' and change the library to the same name.

https://github.com/ElectronicCats/Arduino_Boards_Index/blob/011e044fcaac7bed9a43d79accc06ef3f1ce5939/package_electroniccats_index.json#L77

https://github.com/ElectronicCats/Arduino_Boards_Index/blob/011e044fcaac7bed9a43d79accc06ef3f1ce5939/electroniccats/samd_advanced/libraries/SPI/library.properties#L9

Maybe is a good idea to make a unique architecture to the BastWAN (samr34).

https://github.com/ElectronicCats/Arduino_Boards_Index/blob/011e044fcaac7bed9a43d79accc06ef3f1ce5939/electroniccats/samd_advanced/boards.txt#L183

Don't forget to change the BastWAN board 👍

**Comment by wero1414** [comment]
Thank you @ricaun i will change it

**Comment by wero1414** [comment]
About the  unique architecture can you explain more please? 

Cause i didnt really got you

**Comment by ricaun** [comment]
You have 2 kinds of boards on you samd_advanced.

* Magspoof v3 (SAMD11C14A)
* BastWan (SAMR34J18B)

I suggest you separate the 2 boards and create a unique architecture only for the SAMR34J18B/SAML21. 

Wiz-IO is designing a similar project https://github.com/Wiz-IO/platform-sam-lora

**Comment by sabas1080** [comment]
We can not leave a single core for a single platform, I think it is better to have in a several with similar characteristics a single core, if not in the end it is to install too many cores

SAMR34 and SAML21 are very similar, and they come from the samd21 family

The samr34 family is defined for later work with libraries

**Comment by ricaun** [comment]
@sabas1080 you are probably right, SAMD, SAML, and others have a similar coding and stuff.
