### ISSUE TITLE
DS18B20 sensor with a BastWAN / RAK4260

### ISSUE THREAD

**Issue by 0x524c** [ElectronicCats/Arduino_Boards_Index#27]
Hello, I am trying to use a DS18B20 sensor with a BastWAN / RAK4260.

Could anyone help me with this? I haven't found a driver / library.

**Comment by sabas1080** [comment]
OneWire and DallasTemperature are compatibles

![image](https://user-images.githubusercontent.com/2874292/80004713-49fda600-8488-11ea-88fa-3345bbdd637d.png)
![image](https://user-images.githubusercontent.com/2874292/80004735-51bd4a80-8488-11ea-8d8b-75b90bd9dd75.png)
