### ISSUE TITLE
Can't install from the Arduino Boards Manager: CRC error

### ISSUE THREAD

**Issue by tobozo** [ElectronicCats/Arduino_Boards_Index#33]
tried to delete the cache and staging binaries several times but no luck, does seem more permanent than temporary :-)

![image](https://user-images.githubusercontent.com/1893754/105038511-b3363800-5a5f-11eb-98ae-323f7e0ec076.png)

**Comment by sabas1080** [comment]
Hi @tobozo 
What OS?

**Comment by tobozo** [comment]
hi @sabas1080 this is on Ubuntu Linux x86_64
[edit] Using Arduino 1.8.13

**Comment by sabas1080** [comment]
We have tested a new installation in Ubuntu and ok

S.O Ubuntu 20.01

![Captura_de_pantalla_de_2021-01-19_10-06-32](https://user-images.githubusercontent.com/2874292/105063753-b7535d00-5a41-11eb-8273-f7109f4c8029.png)

**Comment by sabas1080** [comment]
Remove please package_electroniccats_index.json, cache and staging binaries please

**Comment by tobozo** [comment]
still failing on CRC check, this is what I have in the staging folder after the failure

![image](https://user-images.githubusercontent.com/1893754/105065727-7594d780-5a7e-11eb-9e62-75ba614ada38.png)

and this is the last log entry


```log
2021-01-19T16:44:31.303Z INFO c.a.u.n.HttpConnectionManager:157 [ContributionManager Install Thread] Request 
complete URL="https://github.com/ElectronicCats/BOSSA/releases/download/1.0.0-electroniccats-1/bossac-1.0.0-
electroniccats-1-i686-linux-gnu.tar.gz", method=GET, response code=206, request id=278E4F7D984A4E24, headers=
{Accept-Ranges=[bytes], null=[HTTP/1.1 206 Partial Content], Server=[AmazonS3], Content-Range=[bytes 0-34851/34852], 
ETag=["e7954995d8fcc1e00d45b8f2149eb4c8"], Content-Disposition=[attachment; filename=bossac-1.0.0-electroniccats-
1-i686-linux-gnu.tar.gz], Last-Modified=[Wed, 15 Jul 2020 01:09:53 GMT], x-amz-request-id=[A5D3A13B5A5709F6], Content-
Length=[34852], x-amz-id-2=[PTxT0WvsAIKB8pv8MhnSHesdMt+PAhYXVK9MtihfaqEHQwJIPiaSBI35L7VMyAhKpvi8tRjQd4M=],
 Date=[Tue, 19 Jan 2021 16:44:32 GMT], Content-Type=[application/octet-stream]}

```

I'm located in France

**Comment by sabas1080** [comment]
Can you validate checksum this file in your SO? https://github.com/ElectronicCats/BOSSA/releases/download/1.0.0-electroniccats-1/bossac-1.0.0-electroniccats-1-i686-linux-gnu.tar.gz

**Comment by tobozo** [comment]
```
> $ sha256sum bossac-1.0.0-electroniccats-1-i686-linux-gnu.tar.gz 

8dada7994141aaa8deb2fe8f85f70a8cb0de3284d792e4acd298a4d353b5a2f2  bossac-1.0.0-electroniccats-1-i686-linux-gnu.tar.gz

```

**Comment by sabas1080** [comment]
ok, seems to be an error in the checksum of this file for your OS

https://github.com/ElectronicCats/Arduino_Boards_Index/blob/gh-pages/package_electroniccats_index.json#L2059

`8dada7994141aaa8deb2fe8f85f70a8cb0de3284d792e4acd298a4d353b5a2f2`

vs

`edd3bc6fd80641563dc6ca337d695fca25c2d43242172ea0418b678d4dbe0628`

**Comment by sabas1080** [comment]
with MacOS `shasum -a 256 bossac-1.0.0-electroniccats-1-i686-linux-gnu.tar.gz   8dada7994141aaa8deb2fe8f85f70a8cb0de3284d792e4acd298a4d353b5a2f2`
🤔

**Comment by tobozo** [comment]
Same when pasting URL in there:

https://hash.online-convert.com/sha256-generator

sha256sum([url](https://github.com/ElectronicCats/BOSSA/releases/download/1.0.0-electroniccats-1/bossac-1.0.0-electroniccats-1-i686-linux-gnu.tar.gz)) = 8dada7994141aaa8deb2fe8f85f70a8cb0de3284d792e4acd298a4d353b5a2f2

So my OS agrees with your OS and the hash.online-convert tool, looks like the index.json file needs editing :-)

**Comment by sabas1080** [comment]
Yes, @wero1414 will solve this

**Comment by wero1414** [comment]
Hi @tobozo you should be able to do it already! please check

**Comment by tobozo** [comment]
the board installation works fine now, thanks for the reactivity !

closing this issue as solved

**Comment by sabas1080** [comment]
Thanks @tobozo !
