### ISSUE TITLE
Communication error while installing WCH Boards

### ISSUE THREAD

**Issue by sylvain-bouchard** [ElectronicCats/Arduino_Boards_Index#39]
The downloading process fails at around 75% with the following error:

> Downloading packages
> electroniccats:riscv-none-embed-gcc@10.2.0-1.2-xPack
> Failed to install platform: 'electroniccats:wch:0.0.1'.
> Error: 2 UNKNOWN: stream error: stream ID 1; PROTOCOL_ERROR; received from peer

I have tried the individual download URLs listed in the json file located at https://electroniccats.github.io/Arduino_Boards_Index/package_electroniccats_index.json and I am not able to reach any URLs with the host https://www.mattairtech.com as it seems to be down.

**Comment by sabas1080** [comment]
Hi @sylvain-bouchard 

can you give us more information:
What operating system are you using?

the package you are looking for is really on the line
https://github.com/ElectronicCats/Arduino_Boards_Index/blob/gh-pages/package_electroniccats_index.json#L2940

I am noticing that the repository is now archived, but it should work, I will report this to the engineering area.

**Comment by sylvain-bouchard** [comment]
Hello @sabas1080 ,

Thanks for your reply. I am not sure which archive causes the install to fail, but here is some information about my environment:

IDE: Arduino IDE Version: 2.3.2 (Date: 2024-02-20T09:53:59.281Z, CLI Version: 0.35.3)
OS: Mac OS Sonoma 14.5

**Comment by Elizabeth-0** [comment]
Hello @sylvain-bouchard,

Thanks for your response and your patience.

To start troubleshooting, please try the following steps:
- Disable the firewall temporarily.
- Test with different internet connections (e.g., home, work, etc.).
- Restart your PC.
- Reinstall the Arduino IDE.

If the issue continues, could you let us know which chip your device has (e.g., M1, M2, etc.)?

Have a great day!

**Comment by sylvain-bouchard** [comment]
Hello @Elizabeth-0 ,

I have tried it again and it now works! There was probably a host that was temporarily unavailable and is now back online.

Thanks for your help.
